### ISSUE TITLE
The first argument to the function defined by `define-declaration` seems ambiguous

### ISSUE THREAD

**Issue by digikar99** [alex-gutev/cl-environments#9]
About `define-declaration`, [CLTL2](https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node102.html) writes:

> The function defined by this macro will be called with two arguments, a declaration specifier whose car is decl-name and the env argument to augment-environment.

For the following:

```lisp
(define-declaration my-decl (args)
  (print args)
  (values :variable nil))
```

CCL provides the args as a list whose first element is indeed the `decl-name`, while SBCL does not.

```lisp
(augment-environment nil :variable '(x) :declare '((my-decl x)))
; prints (MY-DECL X) on CCL
; prints (X) on SBCL
```

**Comment by alex-gutev** [comment]
Theoretically the `define-declaration` wrapper should remove the CAR of the argument list on CCL, but I guess I didn't implement that. I will fix it, though does the native `define-declaration`, i.e. without the wrapper and code walker, even work on CCL? Last time I tried, which was a while ago, `define-declaration` didn't do anything on CCL, i.e. the declaration function was never called.

**Comment by digikar99** [comment]
Just checked; for both CCL 1.12 and 1.12.1, an explicit use of `ccl:augment-environment` does call the user defined declaration functions, but not otherwise. Compilation of a form like 

```lisp
(let (x)
  (declare (my-decl x))
  x)
```

does not call the user-defined declaration functions; for these we do need the macros in the `cl-environments` package.

**Comment by alex-gutev** [comment]
I've fixed this issue so that the arguments passed to the declaration function are consistent with SBCL and what I've written in the documentation (https://alex-gutev.github.io/cl-environments/#define_declaration), regardless of whether it is called by the code walker or CCL.

I did notice that while CCL does call the declaration function when the declaration is given to `AUGMENT-ENVIRONMENT`, it doesn't actually store anything in the environment. 

````lisp
CL-USER> (define-declaration foo-type (args)
  (destructuring-bind (foo-type &rest vars) args
    (values
     :variable
     (mapcar
      (lambda (var)
	`(,var foo-type ,foo-type))
      vars))))
#<Compiled-function (DEFINE-DECLARATION FOO-TYPE) (Non-Global)  #x3020013084AF>
CL-USER> (let ((env (augment-environment nil :variable '(x) :declare '((foo-type foo1 x)))))
	   (variable-information 'x env))
:LEXICAL
T
NIL
````


I am currently testing on a rather old version of CCL though so maybe they've changed it in newer versions.

**Comment by digikar99** [comment]
> I did notice that while CCL does call the declaration function when the declaration is given to AUGMENT-ENVIRONMENT, it doesn't actually store anything in the environment.

I just checked on CCL 1.12.2. The behavior is still the same.
 
I had once looked into `ccl:variable-information` and the issue seemed to be with how it retrieves the information. Ref https://github.com/Clozure/ccl/issues/421

**Comment by alex-gutev** [comment]
This issue is present on CCL even when using `augment-environment` from cl-environments, since `augment-environment` simply calls into the native CCL implementation. I can replace it with my own implementation which stores the declaration information in the symbol macro, using the `:symbol-macro` argument.

SBCL does store custom declaration information for variables and functions when its added using `augment-environment` however it seems it ignores custom general declarations.

Edit: SBCL does not ignore user-defined general declarations, I was wrong.

**Comment by digikar99** [comment]
That seems reasonable. May be pretty neat even :).

**Comment by alex-gutev** [comment]
I'll keep the issue open until it's completed.

**Comment by alex-gutev** [comment]
Fixed. Now the information from the user-defined declarations should be included in the environment returned by `AUGMENT-ENVIRONMENT`, on CCL.
